call_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('log.urls'), name='log'),
]

log/urls.py
from django.urls import path
from . import views

app_name = 'log'

urlpatterns = [
	path('contact/', views.ContactListView.as_view(), name='contact_list'),
	path('contact/<int:pk>/', views.ContactView.as_view(), name='contact_detail'),
	path('logs/<str:log>/', views.CallListView.as_view(), name='logs'),
	path('contact/edit/<int:pk>/', views.ContactUpdateView.as_view(), name='edit_contact'),
	path('create/', views.ContactCreateView.as_view(), name='contact_create'),
	path('call/', views.CallFormView.as_view(), name='make_call'),
	path('call/<int:pk>/detail/', views.CallView.as_view(), name='call_detail'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
<div>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #e7ff60">
  <a class="navbar-brand glow"><strong>N</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link a" href="{% url 'log:make_call' %}">DIAL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link a" href="{% url 'log:contact_create' %}">CREATE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link a" href="{% url 'log:contact_list' %}">CONTACTS</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle a" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CALL HISTORY
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'log:logs' log='incoming' %}">Incoming</a>
          <a class="dropdown-item" href="{% url 'log:logs' log='outgoing' %}">Outgoing</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'log:logs' log='all' %}">All</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
</div>

<style>
.a {
  font-size: 1.6em;
  text-shadow: 1px 1px 2px black, 0 0 25px pink, 0 0 5px red;
}

.glow {
  font-size: 2em;
  color: #fff;
  text-align: center;
  -webkit-animation: glow 1s ease-in-out infinite alternate;
  -moz-animation: glow 1s ease-in-out infinite alternate;
  animation: glow 2s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
    text-shadow: 0 0 0.4em #67f79c, 0 0 0.5em #67f79c, 0 0 0.6em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c;
  }
  
  to {
    text-shadow: 0 0 0.4em #67f79c, 0 0 0.5em #67f79c, 0 0 1.0.6em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c, 0 0 0.7em #67f79c;
  }
}
</style>

<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10 a">
  {% block content %}
  {% endblock %}
  </div>
</div>


<style type="text/css">
  body {
 background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWlU5pkzll2SyjxxgGtmRRcajQkQ3iPHcdaxp8YZlit8cXeU214A");
   background-position: center;
  background-repeat: no-repeat;
  background-size: cover; 
  }
</style>
	
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>